linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
